title: six ravens
email: hello@sixravens.io 
description: security is culture 
baseurl: ""
url: "https://sixravens.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom settings
logo: /assets/images/logo.png
background_image: /assets/images/background.png

# Navigation
header_pages:
  - about.md
  - projects.md
  - contact.md

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
